#!/bin/bash

which yum > /dev/null

if [ $? -eq 0 ]; then
	sudo yum list installed | grep $1 > /dev/null
	exit $?
else
	which dnf > /dev/null

	if [ $? -eq 0 ]; then
		sudo dnf list installed | grep $1 > /dev/null
		exit $?
	else
		which zypper > /dev/null

        	if [ $? -eq 0 ]; then
			sudo zypper search -ir "$1" /dev/null
			exit $?
		else
			which paclist > /dev/null
			
			if [ $? -eq 0 ]; then
				sudo paclist community | grep $1 /dev/null
				exit $?
			else
				which apt > /dev/null
				
				if [ $? -eq 0 ]; then
					c=$(sudo grep -r Package /var/lib/apt/lists/*) 
					echo "$c" | awk '{print $2;}' | grep $1 > /dev/null
					exit $?
				else
					exit 33
				fi
			fi
		fi	
	fi
fi
