#!/bin/bash

a=("${!1}")
h=("${!2}")

if [[ ${#a[@]} -ne ${#h[@]} && "$a[1]"=="-h" ]]; then
	[[ "$a[1]"=="-h" ]] && echo "1" "${a[1]}" "-h"
	l=${#h[@]}

	for (( i=1; i<${l}+1; i++ )); do
  		echo $i "/" ${l} ": " ${h[$i-1]}
	done

	exit 1
fi