#!/bin/bash

args=("${!1}")
help=("${!2}")

echo $help

if [ ${#args[@]} -ne ${#help[@]} ]; then
	arraylength=${#help[@]}

	for (( i=1; i<${arraylength}+1; i++ )); do
  		echo $i " / " ${arraylength} " : " ${help[$i-1]}
	done
fi