#!/bin/bash

check_installed_package $1

echo "[!] $? install_package $1"
if [ $? -ne 0 ]; then
	echo "[!] install_package $1"
	install_package $1
fi

which $2

if [ $? -ne 0 ]; then
	echo "[!] $2 not found"
	exit 1
fi