#!/bin/bash

args=( "$@" )
help=( "bridge name" "interface 1" "interface 2" )

source check_args 'args[@]' 'help[@]'

sudo ifconfig $2 0.0.0.0
sudo ifconfig $3 0.0.0.0
sudo brctl addbr $1
sudo brctl addif $1 $2
sudo brctl addif $1 $3 
sudo dhclient $1
sudo ifconfig $1 up
