#!/bin/bash

which yum > /dev/null

if [ $? -eq 0 ]; then
	sudo yum -y install $1 > /dev/null
	exit $?
else
	which dnf > /dev/null

	if [ $? -eq 0 ]; then
		sudo dnf -y install $1 > /dev/null
		exit $?
	else
		which zypper > /dev/null

        	if [ $? -eq 0 ]; then
			sudo zypper -y install $1 > /dev/null
			exit $?
		else
			which paclist > /dev/null
			
			if [ $? -eq 0 ]; then
				sudo pacman --noconfirm -S $1 > /dev/null
				exit $?
			else
				which apt > /dev/null
				
				if [ $? -eq 0 ]; then
					sudo apt-get -y install $1 > /dev/null
					exit $?
				else
					exit 44
				fi
			fi
		fi	
	fi
fi
