#!/bin/bash

which yum > /dev/null

if [ $? -eq 0 ]; then
	echo "[!] installing $1"
	sudo yum -y install $1 > /dev/null
	exit $?
fi

which dnf > /dev/null

if [ $? -eq 0 ]; then
	echo "[!] installing $1"
	sudo dnf -y install $1 > /dev/null
	exit $?
fi

which zypper > /dev/null

if [ $? -eq 0 ]; then
	echo "[!] installing $1"
	sudo zypper -y install $1 > /dev/null
	exit $?
fi

which paclist > /dev/null

if [ $? -eq 0 ]; then
	echo "[!] installing $1"
	sudo pacman --noconfirm -S $1 > /dev/null
	exit $?
fi

which apt > /dev/null

if [ $? -eq 0 ]; then
	echo "[!] installing $1"
	sudo apt-get -y install $1 > /dev/null
	exit $?
fi

echo "[E] can't install $1"

exit 44
