#!/bin/bash

mmdevice="/dev/mmcblk0"
ds=""

if [ "$1" != "" ]; then
	mmdevice="$1"
fi

if [ -f $mmdevice ]; then
	echo "[E] devie '$mmdevice' not found"
	exit 1
fi

if [ $mmdevice =~ "[0-9]$" ]; then
	ds="p"
fi	

source check_internet

if [ $? -ne 0 ]; then
	echo "[E] you are offline"
	exit 2
fi

xzcat CentOS-Userland-7-armv7hl-RaspberryPI-Minimal-1810-sda.raw.xz | dd of=$mmdevice bs=4M
sync

mount ${mmdevice}${ds}3 /mnt
cd /mnt
tar cfz ~/pi.tgz . --no-selinux
cd
umount /mnt

echo "unit s
print free
rm 3
rm 2
print free
mkpart
set
print free
quit
" | parted $mmdevice

mkfs.ext4 ${mmdevice}${ds}2

mount ${mmdevice}${ds}2 /mnt
tar xfz ~/pi.tgz -C /mnt --no-selinux

rm ~/pi.tgz

echo "
Отключаем SELinux в /mnt/etc/selinux/config:

SELINUX=disabled


Редактируем /mnt/etc/fstab, оставляя в нем только две записи о разделах: загрузочный (/boot, без изменений) и корневой (изменяем значение UUID, которое можно узнать, изучив вывод команды blkid на Linux-е):

UUID=6a1a0694-8196-4724-a58d-edde1f189b31  /     ext4    defaults,noatime 0 0
UUID=6938-F4F2                             /boot vfat    defaults,noatime 0 0


Наконец, изменяем параметры загрузки ядра: указываем новое расположение корневого раздела, отключаем вывод отладочной информации и (опционально) запрещаем ядру назначать IPv6 адреса на сетевых интерфейсах:

# cd
# umount /mnt
# mount /dev/mmcblk0p1 /mnt


Приводим содержимое /mnt/cmdline.txt к следующему виду (одна строка без переносов):

root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait quiet ipv6.disable_ipv6=1


Готово:

# cd
# umount /mnt
# sync

Переставляем microSD в «малинку», запускаем и получаем к ней сетевой доступ по ssh (root/centos).
"

