#!/bin/bash

ssh $1 ". ~/.bashrc; echo \$PATH | grep '~/bin'"
l="export PATH=\$PATH:~/bin"

if [ $? -ne 0 ]; then
	ssh $1 "cat ~/.bashrc | grep '$l'"
	if [ $? -ne 0 ]; then
		echo "[!] adding bin path to ~/.bashrc ~/.profile"
		ssh $1 "echo 'export PATH=\$PATH:~/bin' >> ~/.bashrc"
		ssh $1 "echo 'export PATH=\$PATH:~/bin' >> ~/.profile"
	fi
fi

ssh $1 ". ~/.bashrc; echo \$PATH | grep '~/bin'"

if [ $? -ne 0 ]; then
	echo "[E] ~/bin not found in PATH"
	exit 1
fi

ssh $1 "if [ -d ~/bin ]; then exit 0; else exit 1; fi"

if [ $? -ne 0 ]; then
        scp -r ~/bin $1:~/
fi


