#!/bin/bash

args=( "$@" )
help=( "user@10.0.0.1" "ssh root password" "remote path" "local path" )

source check_args 'args[@]' 'help[@]'

source ssh_check_bin_dir $1 $2

source check_installed_package_and_program colordiff colordiff

f1=$(mktemp)
f2=$(mktemp)

echo "[!] calculating hash for $1 $3 in $f1"
echo "$(ssh_hash_sum_of_each_item_in_dir $1 $2 $3)" > $f1
echo "[!] calculating hash for $4 in $f2"
echo "$(hash_sum_of_each_item_in_dir $4)" > $f2

colordiff $f1 $f2

r=$?

if [ $r -eq 0 ]; then
	echo "[+] There is no difference"
fi

exit $r
