#!/bin/bash

args=( "$@" )
help=( "user@10.0.0.1" "root_password" "package name" "program name" )

source ssh_check_bin_dir $1

ssh $1 "$p check_installed_package $3"

if [ $? -ne 0 ]; then
	ssh $1 "$p install_package $3"
fi

ssh $1 "$p which $4 > /dev/null"

if [ $? -ne 0 ]; then
	echo "[!] $4 not found"
	exit 1
fi