#!/bin/bash

a=($(echo $1 | tr '/' "\n"))
d="${a[1]}"
if [ "" != "$2" ]; then
	d=$2
fi
if [ -d $d ]; then
	rm -ri $d
fi
mkdir $d
cd $d
vagrant="env -u GEM_HOME -u GEM_PATH vagrant"
$vagrant init $1
if [ $? -eq 0 ]; then
	$vagrant up
fi
if [ $? -eq 0 ]; then
	$vagrant ssh
fi
