#!/bin/bash

args=( "$@" )
help=( "file path" )

source check_args 'args[@]' 'help[@]'

h="sha1sum"

if [ "$2" != "" ]; then
	h="$2"
fi

find $1 -type f -print0 | sort -z | xargs -0 $h | $h | cut -d' ' -f1
