#!/bin/bash

for i in {1..254} ;do (ping 192.168.31.$i -c 1 -w 5  >/dev/null && echo "[+] 192.168.31.$i $(host 192.168.31.$i)" &) ;done

exit

if [ "$1" != "" ]; then
	#c=$()
	ping -c 1 $1 > /dev/null 
	if [ "$?" -eq "0" ]; then 
		echo "[+] $1 $(host $1)"; 
	fi;	
else
	for (( i=1; i<255; i++ )); do 
		ip="192.168.31.$i";
		$0 $ip
	done;
fi;
